# .goreleaser.yml
project_name: f5ltm_exporter
builds:
  - id: "f5ltm_exporter"
    env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
      - -X main.release={{.Version}}-{{.Commit}}
    goos:
      - linux
      - windows
    goarch:
      - amd64

    dir: .
    main: ./cmd/f5ltm_exporter/
    binary: f5ltmexporterserver